# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/workspace/circCarto/Cartograms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/workspace/circCarto/Cartograms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/workspace/circCarto/Cartograms/CMakeFiles /home/jan/workspace/circCarto/Cartograms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/workspace/circCarto/Cartograms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arrangement_2

# Build rule for target.
arrangement_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrangement_2
.PHONY : arrangement_2

# fast build rule for target.
arrangement_2/fast:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/build
.PHONY : arrangement_2/fast

# target to build an object file
MyWindow_files.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_files.o
.PHONY : MyWindow_files.o

# target to preprocess a source file
MyWindow_files.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_files.i
.PHONY : MyWindow_files.i

# target to generate assembly for a file
MyWindow_files.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_files.s
.PHONY : MyWindow_files.s

# target to build an object file
MyWindow_operations.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_operations.o
.PHONY : MyWindow_operations.o

# target to preprocess a source file
MyWindow_operations.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_operations.i
.PHONY : MyWindow_operations.i

# target to generate assembly for a file
MyWindow_operations.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_operations.s
.PHONY : MyWindow_operations.s

# target to build an object file
MyWindow_overlay.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_overlay.o
.PHONY : MyWindow_overlay.o

# target to preprocess a source file
MyWindow_overlay.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_overlay.i
.PHONY : MyWindow_overlay.i

# target to generate assembly for a file
MyWindow_overlay.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/MyWindow_overlay.s
.PHONY : MyWindow_overlay.s

# target to build an object file
arrangement_2.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/arrangement_2.o
.PHONY : arrangement_2.o

# target to preprocess a source file
arrangement_2.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/arrangement_2.i
.PHONY : arrangement_2.i

# target to generate assembly for a file
arrangement_2.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/arrangement_2.s
.PHONY : arrangement_2.s

# target to build an object file
cartograms.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/cartograms.o
.PHONY : cartograms.o

# target to preprocess a source file
cartograms.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/cartograms.i
.PHONY : cartograms.i

# target to generate assembly for a file
cartograms.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/cartograms.s
.PHONY : cartograms.s

# target to build an object file
demo_tab.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/demo_tab.o
.PHONY : demo_tab.o

# target to preprocess a source file
demo_tab.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/demo_tab.i
.PHONY : demo_tab.i

# target to generate assembly for a file
demo_tab.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/demo_tab.s
.PHONY : demo_tab.s

# target to build an object file
forms.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/forms.o
.PHONY : forms.o

# target to preprocess a source file
forms.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/forms.i
.PHONY : forms.i

# target to generate assembly for a file
forms.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/forms.s
.PHONY : forms.s

# target to build an object file
qt_layer.o:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/qt_layer.o
.PHONY : qt_layer.o

# target to preprocess a source file
qt_layer.i:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/qt_layer.i
.PHONY : qt_layer.i

# target to generate assembly for a file
qt_layer.s:
	$(MAKE) -f CMakeFiles/arrangement_2.dir/build.make CMakeFiles/arrangement_2.dir/qt_layer.s
.PHONY : qt_layer.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... arrangement_2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyWindow_files.o"
	@echo "... MyWindow_files.i"
	@echo "... MyWindow_files.s"
	@echo "... MyWindow_operations.o"
	@echo "... MyWindow_operations.i"
	@echo "... MyWindow_operations.s"
	@echo "... MyWindow_overlay.o"
	@echo "... MyWindow_overlay.i"
	@echo "... MyWindow_overlay.s"
	@echo "... arrangement_2.o"
	@echo "... arrangement_2.i"
	@echo "... arrangement_2.s"
	@echo "... cartograms.o"
	@echo "... cartograms.i"
	@echo "... cartograms.s"
	@echo "... demo_tab.o"
	@echo "... demo_tab.i"
	@echo "... demo_tab.s"
	@echo "... forms.o"
	@echo "... forms.i"
	@echo "... forms.s"
	@echo "... qt_layer.o"
	@echo "... qt_layer.i"
	@echo "... qt_layer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

